version: '3.8'

services:
  sol_listener:
    image: sol_listener:latest
    restart: always
  sol_db:
    image: sol_db:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: '32GB'

networks:
  sol_network:
    driver: bridge
